version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "5102:27017"

  botman2000/python_back:
    build: 
      context: C:\Users\Cristi\Desktop\createx\createx_back
      dockerfile: Dockerfile
    container_name: python_api_back
    ports:
      - "5103:5103"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/"
      DATABASE_NAME: "CreatexDatabase"

  botman2000/simple-html-page:
    build: 
      context: C:\Users\Cristi\Desktop\createx\createx_front
      dockerfile: Dockerfile
    container_name: front_createx
    ports:
      - "8080:80"