apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-html-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-html-page
  template:
    metadata:
      labels:
        app: simple-html-page
    spec:
      containers:
      - name: simple-html-page
        image: botman2000/createx_front
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-html-page
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80

  selector:
    app: simple-html-page
